node_name       : My_Node
states          : ['INACTIVE', 'UNCONFIGURED', 'INACTIVE', 'ACTIVE', 'INACTIVE', 'UNCONFIGURED', 'ACTIVE', 'UNCONFIGURED']
timeout         : 3
delay           : 1
publications    : ['/My_Node/chatter']
publishing_hz   : [10]
subscriptions   : ['/My_Node/noise']
services        : ['/My_Node/example_service']
